spring:
  profiles:
    include: secret
  data:
    mongodb:
      uri: mongodb://localhost:27017/mydatabase?authSource=admin

    redis:
      host: localhost
      port: 6379
      password: secret

  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver

